version: '3'

services:
  mysql:
    container_name: ${DB_CONTAINER_NAME}
    image: 'mysql:8.0'
    healthcheck: 
      test: "exit 0"
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
